covidtrackingapi:
  allstates:
    stats:
      url: https://api.covidtracking.com/v1/states/current.json
    metadata:
      url: https://api.covidtracking.com/v1/states/info.json

  singlestate:
    stats:
      url: https://api.covidtracking.com/v1/states/%s/%s.json
